### ISSUE TITLE
Building on Debian Jessie

### ISSUE THREAD

**Issue by msroest** [nm-l2tp/network-manager-l2tp#10]
Hi,
   Trying to get your plugin to build on debian Jessie and running into all kinds of dependency failures.  Any tips or a suggestion of a version that will work?

Thanks

**Comment by dkosovic** [comment]
For NetworkManager 1.0 (or 0.9) based linux distributions, don't use the master branch, but use the nm-1-0 branch, like version 1.0.2 tag or later checkins in that branch. Version 1.2.xon the master branch is intended for NetworkManger 1.2 (or 1.1) based linux distributions.

For dependencies, I think the following should do it:
```sh
sudo apt install \
intltool \
libtool \
network-manager-dev \
libnm-util-dev \
libnm-glib-dev \
libnm-glib-vpn-dev \
libnm-gtk-dev \
libnm-dev \
libnma-dev \
ppp-dev \
libdbus-glib-1-dev \
libsecret-1-dev \
libgtk-3-dev \
libglib2.0-dev \
xl2tpd \
strongswan
```
Sorry don't have Jessie handy in front of me, so not 100% sure on the package names that incorporate a version number are correct.

**Comment by msroest** [comment]
Perfect thanks that seems to have worked to get through autogen.sh and configure
