### ISSUE TITLE
problem after connect (no internet access)

### ISSUE THREAD

**Issue by codex7** [nm-l2tp/network-manager-l2tp#102]
i successfully connected via nm but i have a problem
when connected to vpn, there was no internet access 
i marked:
> Use this connection only for resources on its network

but i cant ping local IP such as 10.10.x.x 
please help

**Comment by dkosovic** [comment]
Sounds like you are missing the necessary entries in the routing table.

In the IPv4 section of the VPN connection you can add static routes.

Alternatively have a look at the `/etc/ppp/ip-up.d/01-routes.sh` example at end of issue #75.

Alternatively if you are able to configure the VPN network's DHCP server, you can use DHCP option 121 (or maybe even option 33) to push the routes to the VPN clients, assuming `dhclient` is configured correctly by either yourself or your linux distro.

**Comment by dkosovic** [comment]
Sorry I wasn't of much help, routing related issues can be a pain to diagnose.

If you need to re-open, just replay.

I'm just doing some bookkeeping and closing issues.
