### ISSUE TITLE
Can't find libnm and libnma dependencies.

### ISSUE THREAD

**Issue by 9thDimension** [nm-l2tp/network-manager-l2tp#19]
```
configure: error: Package requirements (libnma >= 1.1.0) were not met:

No package 'libnma' found
```
And when I try to get them with apt-get:
`E: Unable to locate package libnma
`
What do I do?

**Comment by dkosovic** [comment]
I'm guessing you are using a NetworkManager 0.9 or 1.0 based linux distribution. In which case, use the nm-1-0 branch of this repository, i.e : 

    git checkout nm-1-0
