### ISSUE TITLE
libnma not found

### ISSUE THREAD

**Issue by alexchernokun** [nm-l2tp/network-manager-l2tp#24]
Hello,

I'm having an issue while installing networkmanager-l2tp via yaourt.
Here is the output of the error:

```
configure: error: Package requirements (libnma >= 1.1.0) were not met:

No package 'libnma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBNMA_CFLAGS
and LIBNMA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build networkmanager-l2tp.
```

I was trying to find libnma package on the aur and no luck. 
Could you please help me with this?
Thank you in advance

**Comment by dkosovic** [comment]
libnma is part of NetworkManager 1.1 and later.

If you are using NetworkManager 1.0,x, you could use NetworkManager-l2tp-1.0.x

I would also recommend using libreswan instead of strongswan for the IPsec support.

**Comment by alexchernokun** [comment]
I've checked the NM version:
```
╰─ pacman -Si networkmanager
Repository      : extra
Name            : networkmanager
Version         : 1.4.2-1
Depends On      : libnm-glib  iproute2  polkit  wpa_supplicant  libsoup  libmm-glib  libnewt  libndp  libteam
```

So have I understood you correctly: libnma should have been already installed?

**Comment by dkosovic** [comment]
Wow, I didn't know NetworkManager 1.4.0 had been release, let alone 1.4.2.

I don't know why libnma is missing with NetworkManager 1.4.2.

I usually track the Gnome upstream changes to network-manager-pptp changes and incorporate back into nm-l2tp, but I don't see any NM 1.4.x specific changes yet :
  https://git.gnome.org/browse/?q=network-manager

I'm pretty sure NM 1.4 was supposed to be backward compatible with NM 1.2 and the Gnome NetworkManager VPN plug-ins weren't going to track the NM version number anymore.

Will look more into it.

**Comment by alexchernokun** [comment]
Thank you! Will wait for the update from you.

**Comment by dkosovic** [comment]
Extract from https://blogs.gnome.org/lkundrak/2016/08/24/networkmanager-1-4/ :

> VPN plugins are no longer released together with NetworkManager. It is intended that for most 
> plugins no 1.4.0 release exists because the newest version of the plugin works equally well with 
> any NetworkManager version 1.2.0 or newer.

Guess I'll have to try things out on the latest update of Arch Linux and get back to you.

**Comment by alexchernokun** [comment]
Thanks!

**Comment by dkosovic** [comment]
Could you try installing the same dependencies as networkmanager-pptp (apart from pptpclient which isn't required)  :
https://www.archlinux.org/packages/extra/x86_64/networkmanager-pptp/

The dependencies for networkmanager-l2tp in AUR look a bit dated in comparison, since some of the listed APIs have been superseeded.

**Comment by alexchernokun** [comment]
Already have networkmanager-pptp installed in the system.
Rechecked and here are the versions:
networkmanager-pptp - Version: 1.2.4-1
libnm-glib  - Version: 1.4.2-1
libsecret - Version: 0.18.5-1
ppp - Version: 2.4.7-2
pptpclient - Version: 1.8.0-2
git - Version: 2.10.1-1
intltool - Version: 0.51.0-1
python  - both 3.5 and 2.7

**Comment by alexchernokun** [comment]
Hm, strange but finally it worked!
First I installed nm-connection-editor and then reinstalled networkmanager-pptp and after that I was able to install networkmanager-l2tp. 
Thank you for the help!
