### ISSUE TITLE
make on Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by GreedyBytes** [nm-l2tp/network-manager-l2tp#25]
Hi,

the make command gives me following output with Ubuntu 16.04:

> $ make
> make  all-recursive
> make[1]: Entering directory '/home/andreas/network-manager-l2tp'
> Making all in shared
> make[2]: Entering directory '/home/andreas/network-manager-l2tp/shared'
> make[2]: Nothing to be done for 'all'.
> make[2]: Leaving directory '/home/andreas/network-manager-l2tp/shared'
> Making all in properties
> make[2]: Entering directory '/home/andreas/network-manager-l2tp/properties'
> Makefile:618: ../shared/nm-utils/.deps/libnm_vpn_plugin_l2tp_la-nm-vpn-plugin-utils.Plo: No such file or directory
> make[2]: *** No rule to make target '../shared/nm-utils/.deps/libnm_vpn_plugin_l2tp_la-nm-vpn-plugin-utils.Plo'.  Stop.
> make[2]: Leaving directory '/home/andreas/network-manager-l2tp/properties'
> Makefile:565: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/andreas/network-manager-l2tp'
> Makefile:434: recipe for target 'all' failed
> make: *** [all] Error 2

Please let me know if I could provide further information.

Thanks for any help.

**Comment by dkosovic** [comment]
can you confirm  you have done the following in the master branch before issuing `make` ?
```
git pull

./autogen.sh

./configure \
  --disable-static --prefix=/usr \
  --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu \
  --libexecdir=/usr/lib/NetworkManager \
  --localstatedir=/var \
  --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7
```

**Comment by GreedyBytes** [comment]
First of all, thank you very much for your fast response.

I don't know what I was doing wrong, because I've done this yesterday in the same order.

After removing the whole directory and trying it again with the steps you described above, it works without an error. 

Keep up the good work. I really appreciate it :+1:
