### ISSUE TITLE
add dependencies to readme

### ISSUE THREAD

**Issue by ftes** [nm-l2tp/network-manager-l2tp#26]
I would suggest adding required libraries for common platforms to the Readme.
Otherwise a tedious `./autogen.sh` roundtrip is required to look at all the errors and figure out what to install.

For ubuntu 16.10 this is `sudo apt install libglib2.0-dev libtool intltool ppp-dev build-essential libgtk-3-dev libnma-dev libsecret-1-dev libnm-gtk-dev libnm-glib-vpn-dev`

**Comment by dkosovic** [comment]
I've moved the Debian and Ubuntu known issues (which includes package dependencies) to https://github.com/nm-l2tp/network-manager-l2tp/wiki and will put a link in the readme file to it.

I will put some of the other Linux distributions up there as well. 

I will put the link in the readme file before I release NetworkManager-l2tp 1.2.4 which may be in the next few days.
