### ISSUE TITLE
undefined symbol: nma_utils_setup_password_storage

### ISSUE THREAD

**Issue by roadriverrail** [nm-l2tp/network-manager-l2tp#28]
Hi, all.  I'm on Ubuntu 15.10.  I followed the build instructions from the readme as well as the "known issues" page.  Everything makes and installs, but there's a crash on creating a new L2TP connection profile.  journalctl shows this:

Nov 23 16:58:18 downhome gnome-session[1536]: /usr/bin/nm-connection-editor: symbol lookup error: /usr/lib/x86_64-linux-gnu/NetworkManager/libnm-l2tp-properties.so: undefined symbol: nm

**Comment by dkosovic** [comment]
might be related to modifications I did to the _nm-1-0_ branch a couple of days ago in the properties folder.

Could you try the following to checkout the latest stable release in the _nm-1-0_ branch:

    git checkout 1.0.4

then do autogen.sh and configure again.

**Comment by roadriverrail** [comment]
That looks like it.  I can now get through to the next  window.

**Comment by dkosovic** [comment]
The untruncated error message is :
```
nm-connection-editor: symbol lookup error: /usr/lib/x86_64-linux-gnu/NetworkManager/libnm-l2tp-properties.so: undefined symbol: nma_utils_setup_password_storage
```

Looks like Ubuntu 15.10 and earlier come with an older version of libnm-gtk that doesn't include nma_utils_setup_password_storage(). Will see if I can add a local implantation of nma_utils_setup_password_storage() if the configure script can't detect the function.

**Comment by dkosovic** [comment]
fixed with commit https://github.com/nm-l2tp/network-manager-l2tp/commit/5bd424300fd343813301d130aa468b7ec2b00fc1 in the _nm-1-0_ branch
