### ISSUE TITLE
autoreconf: not found

### ISSUE THREAD

**Issue by greenSnot** [nm-l2tp/network-manager-l2tp#29]
```
➜  network-manager-l2tp git:(master) ./autogen.sh    
./autogen.sh: 17: ./autogen.sh: autoreconf: not found

```

**Comment by dkosovic** [comment]
You need to install the autoreconf package that contains /usr/bin/autoreconf.

If you are using Debian or Ubuntu you can see the required packages in the wiki :
* https://github.com/nm-l2tp/network-manager-l2tp/wiki

**Comment by greenSnot** [comment]
thanks

**Comment by greenSnot** [comment]
And I can't find libnma-dev libnm-dev on ubuntu 14.04 anyone is able to run on it?
