### ISSUE TITLE
pppd not recognizing option 'lock'

### ISSUE THREAD

**Issue by yejingchen** [nm-l2tp/network-manager-l2tp#4]
I recently updated to `networkmanager-l2tp` 1.0.0 on my Archlinux and installed `libreswan`, but since then I cannot connect to my VPN of my school anymore. My school's VPN doesn't use ipsec.

Package versoins:
networkmanager-l2tp 1.0.0-1
libreswan 3.17-1
ppp 2.4.7-2

Running `nmcli c up myvpn` gives:
`Error: failed activating connection: connection trial timeout.` after waiting for about 30s.

This is NetworkManager's journal:
https://gist.github.com/yejingchen/cb36b56250674b0de4c3f4e2a127ac00

I think that the "unrecognized option 'lock' " might be the key,

**Comment by dkosovic** [comment]
All versions of NetworkManager-l2tp going back many years to 0.1 have used the following code in src/nm-l2tp-service.c :
    write_config_option (pppopt_fd, "lock\n");
to write the lock option to the ppp options file, so I suspect something else is going wrong. The lock option is to ensure exclusive access.

Could post the contents of /var/run/nm-ppp-options.xl2tpd.11964 ?

**Comment by yejingchen** [comment]
That file disappears after the nmcli command fails. I will try to get it
later.
2016年4月26日 17:31，"Douglas Kosovic" <notifications@github.com>写道：

**Comment by yejingchen** [comment]
Sorry for the delay. This is the content of nm-ppp-options.xl2tpd.1862 (the last number may be some process' pid)
```
/var/run $ sudo cat nm-ppp-options.xl2tpd.1862
ipparam nm-l2tp-service-1862
nodetach
lock
usepeerdns
noipdefault
nodefaultroute
noauth
noccp
name 3150101168
lcp-echo-failure 0
lcp-echo-interval 0
plugin /usr/lib/pppd/2.4.7/nm-l2tp-pppd-plugin.so
/var/run $
```

**Comment by dkosovic** [comment]
I don't see anything obviously wrong with it and also checked with the pppd 2.4.7 I had installed by issuing :
   sudo pppd file nm-ppp-options.xl2tpd.1862

pppd didn't complain about the lock option, only thing I changed was the name option to be a local username.

I could try installing Archlinux to reproduce the issue. I wonder if UUCP style locks were enabled with pppd and the kernel.

**Comment by dkosovic** [comment]
I tried the following on a fresh install of Arch Linux i686 on VMWare Workstation : 
    sudo pppd file ./nm-ppp-options.xl2tpd.1862

I get gibberish to stdout as expected, but I'm not able to reproduce the unrecognized option 'lock' issue. I just removed the param and plugin lines also supplied a local username for the name option. I have ppp-2.4.7-2 installed.

**Comment by yejingchen** [comment]
Maybe invoking pppd by `nmcli c up myvpn` works?

**Comment by dkosovic** [comment]
I'll try building NetworkManager-l2tp 1.0.0 from source tomorrow, I don't have access to the VM where I installed Arch Linux now.

networkmanager-l2tp on the following page :
   https://aur.archlinux.org/packages/networkmanager-l2tp/
has been upgraded to version 1.2.0 which has issues and is intended for NetworkManager 1.2 which hasn't been released yet. Latest NetworkManager is currently 1.1.93 (i.e. 1.2-RC1).

**Comment by dkosovic** [comment]
I did reproduce the 'lock' issue. Will try using xltpd from the command-line to see if I'm able to reproduce.

**Comment by dkosovic** [comment]
Please downgrade to the Arch Linux xl2tpd-1.3.6-1 package which doesn't exhibit the 'lock' bug.

It's definitely a bug with xl2tpd-1.3.7-1 and don't need to use NetworkManager-l2tp to trigger the bug. Arch Linux upgraded to that version a week ago, other Linux distributions that I checked are still using 1.3.6.
