### ISSUE TITLE
Error when Installing l2tp by ppa 

### ISSUE THREAD

**Issue by JackieTseng** [nm-l2tp/network-manager-l2tp#41]
Hi, I used the ppa method to install and got this error when I create L2TP.
```
Could not create connection
```
```
Could not load editor VPN plugin for 'org.freedesktop.NetworkManager.l2tp' (missing plugin file "/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-vpn-plugin-l2tp-edito...").
```
According to this error, I try the following commands though still not working either.
```
sudo apt install network-manager-dev libnm-util-dev libnm-glib-dev libnm-glib-vpn-dev libnm-gtk-dev libnm-dev
```

What should I do? Thanks!

**Comment by dkosovic** [comment]
Those _*-dev_ packages are just for building from source code, you shouldn't need them for the PPA packages.

Which Ubuntu version, 32 or 64bit? I assume 64 bit. From one of the error messages, sounds like the following file never got packaged up:
```
/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-vpn-plugin-l2tp-editor.so
```

Once I know which Ubuntu version you are using, I'll try and reproduce.

**Comment by JackieTseng** [comment]
@dkosovic My version is Ubuntu 16.04, 64bit

**Comment by JackieTseng** [comment]
@dkosovic My version is Ubuntu 16.04, 64bit

**Comment by dkosovic** [comment]
That missing `libnm-vpn-plugin-l2tp-editor.so` file  is owned by the network-manager-l2tp-gnome package as confirmed by the following :
```
$ dpkg -S /usr/lib/x86_64-linux-gnu/NetworkManager/libnm-vpn-plugin-l2tp-editor.so
network-manager-l2tp-gnome: /usr/lib/x86_64-linux-gnu/NetworkManager/libnm-vpn-plugin-l2tp-editor.so
```
I've had one GNOME user that had to restart GNOME Shell for it to pickup the plug-in. I wasn't able to reproduce using Unity.

Is there any difference if you run `/usr/bin/nm-connection-editor` directly on the command-line?

**Comment by JackieTseng** [comment]
@dkosovic I am using ubuntu 16.04 LTS.
By running the command you provide, I get this
```
jackie@jackie-pc:~$ /usr/bin/nm-connection-editor 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```
and a Network Connections Window

**Comment by dkosovic** [comment]
I meant to say in addition, with `/usr/bin/nm-connection-editor` are then able to add a L2TP VPN connection ?

Is the missing /usr/lib/x86_64-linux-gnu/NetworkManager/libnm-vpn-plugin-l2tp-editor.so file (which is from the network-manager-l2tp-gnome package package) actually installed?

**Comment by JackieTseng** [comment]
@dkosovic Ah-ha, I reinstall network-manager-l2tp-gnome package, and this time L2TP works! Thanks!
