### ISSUE TITLE
L2TP not showing up in network manager after install from source or PPA (Ubuntu 16.04.2 LTS)

### ISSUE THREAD

**Issue by Nictrasavios** [nm-l2tp/network-manager-l2tp#43]
After compiling from source as per directions on the page, checking the wiki for any solutions and attempting every fix I could find by google - L2TP does not show in network manager.

![screenshot-20170503162032-340x307](https://cloud.githubusercontent.com/assets/5385882/25677471/75c838ae-301c-11e7-9605-1fdf379e8a89.png)

**Comment by dkosovic** [comment]
With the PPA, can you confirm you installed both the `network-manager-l2tp` and `network-manager-l2tp-gnome` packages ?

I'm not familiar with what the GUI is in the screendump you've shown, I don't think I see it from the Unity desktop on Ubuntu 16.04 LTS. What desktop environment are you using?

If you run `/usr/bin/nm-connection-editor` and then try to add a VPN connection, does "_Point-to-Point Tunneling  Protocol (L2TP)_" show?

I know one person had issues with it not showing under GNOME on Ubuntu 17.04 and had to restart the GNOME shell for it to appear. Perhaps you might like to logout/login of the desktop environment or restart and see if it changes anything.

If you are building from source and you are using a 32bit Ubuntu, for the configure arguments change `--libdir=/usr/lib/x86_64-linux-gnu` to `--libdir=/usr/lib` or don't specify it.

The output of the following command might give hinst as to what is going wrong :
```
journalctl --boot
```

**Comment by supermoyj** [comment]
I have a same problem on Ubuntu 16.04LTS（64 bit）.L2TP not showing up in network manager after insall from PPA.The network-manager-l2tp and network-manager-l2tp-gnome was installed and  "Point-to-Point Tunneling Protocol (L2TP)" not showing up when i run /usr/bin/nm-connection-editor.Can you give me some suggestions? Thank you very mush.

**Comment by dkosovic** [comment]
The following file is responsible for advertising  "Point-to-Point Tunneling Protocol (L2TP)"
```
/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-vpn-plugin-l2tp.so
```
Do you see any error messages in `journalctl` output or `nm-connection-editor` regarding libnm-vpn-plugin-l2tp.so ? Maybe issue the following to check :
```
journalctl | grep l2tp
```

I've just issued the following to get the latest packages and I'm still not able to reproduce the issue on 64bit Ubuntu 16.04 :
```
sudo apt update
sudo apt upgrade
```

With the https://github.com/nm-l2tp/network-manager-l2tp/commit/5e1bb6fdb2d15a053532b4e2efad20ecc086a8a2 commit, I replaced all instances of "Point-to-Point Tunneling Protocol" string with "Layer 2 Tunneling Protocol" in all of the files. But that doesn't have an impact on your situation.

**Comment by dkosovic** [comment]
Do you still have the same issue with the new network-manager-l2tp and network-manager-l2tp-gnome 1.2.6 PPA packages ?

**Comment by dragon788** [comment]
If you have installed them but not rebooted your system you need to CLOSE out of the Settings dialog (eg if you were in Settings>Network and trying to add the L2TP VPN), then run `sudo service NetworkManager restart` or `sudo service network-manager restart` in order to respawn the process in the system tray and allow the NetworkManager to load the L2TP plugin. Now if you click on Network Settings and add a VPN it should show L2TP as an option.

**Comment by dkosovic** [comment]
I will update the known issues wiki with some of the issues why it doesn't appear.
