### ISSUE TITLE
Plugin not displaying in Network Manager Drop Down

### ISSUE THREAD

**Issue by azretd** [nm-l2tp/network-manager-l2tp#5]
After a successful autogen, configure, make, and make install, I am unable to get the connection dialogue in the Network Manager on Ubuntu 16.04. Is there anything I can try here?

**Comment by dkosovic** [comment]
Fixes are now in the master branch, but now there is a strongswan issue to solve.

On Ubuntu 16.04 x86-64 I've been using the following configure line :

./configure --prefix=/usr \
--sysconfdir=/etc --localstatedir=/var \
--libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu \
--with-pppd-plugin-dir=/usr/lib/pppd/2.4.7 --enable-absolute-paths

then after a make install I find I have more success if I issue :

  sudo systemctl restart NetworkManager.service

**Comment by dkosovic** [comment]
The fixes are in the master branch and a new NetworkManager-l2tp-1.2.2 will be getting released in the next day or so.

The xl2tpd that ships with Ubuntu 16.04 has issues especially if using L2TP/IPSec, building xl2tpd from source code is a workaround.

The Ubuntu 16.04 xl2tpd package was built using the output of the following command :
$ dpkg-buildflags --get CFLAGS
-g -O2 -fstack-protector-strong -Wformat -Werror=format-security

Unfortunately the -fstack-protector-strong switch is causing unfortunate side-effects which prevents establishing a L2TP/IPSec connection. I'm still investigating and will report the bug upstream.
