### ISSUE TITLE
usepeerdns is always set to pppd

### ISSUE THREAD

**Issue by jtblanton** [nm-l2tp/network-manager-l2tp#52]
There's no way to disable the usepeerdns flag to pppd.  I believe that, when the IPv4 Settings Method "Automatic (VPN) Addresses Only" mode is set, this flag should be dropped from the configuration file so that DNS entries aren't overridden.

**Comment by dkosovic** [comment]
Thanks for the bug report.

I believe the issue has been fixed with commit# https://github.com/nm-l2tp/network-manager-l2tp/commit/7328971a08d897641661e6d2539bc44351909a1d

**Comment by jtblanton** [comment]
I have verified that commit# 7328971 fixes the bug on Ubuntu 16.04 (NM 1.2.6-0ubuntu0.16.04.1).  I used your PPA and plucked just this patch into the 1.2.6 source, and all is well.

Thank you so much for your prompt patch!  I didn't expect for anyone else to fix this; I was intending to write a patch today, as I didn't have time yesterday when I found the issue.  Wonderful support!
