### ISSUE TITLE
Gnome 3.25+ compatibility

### ISSUE THREAD

**Issue by frol** [nm-l2tp/network-manager-l2tp#55]
It seems that something around passwords storage has been changed in Gnome 3.25 (development branch, which is expected to be released as stable 3.26 in September). If I use either of "Store the password only for this user" or "Ask for this password every time", I get the following messages in my journal and the connection doesn't get established:

```
NetworkManager[3100]: <info>  [1501680681.0472] vpn-connection[0x1c3a690,00cc105b-5927-4720-8747-423d980c3107,"MyVPN",0]: Started the VPN service, PID 8139
NetworkManager[3100]: <info>  [1501680681.0520] vpn-connection[0x1c3a690,00cc105b-5927-4720-8747-423d980c3107,"MyVPN",0]: Saw the service appear; activating connection
gnome-shell[22864]: JS ERROR: error while reading VPN plugin output keyfile: GLib.KeyFileError: Key file does not have group “V”
                                             VPNRequestHandler<._showNewStyleDialog@resource:///org/gnome/shell/ui/components/networkAgent.js:522:29
                                             wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                             VPNRequestHandler<._readStdoutNewStyle/<@resource:///org/gnome/shell/ui/components/networkAgent.js:487:17
gnome-shell[22864]: JS ERROR: error while reading VPN plugin output keyfile: GLib.KeyFileError: Key file does not have group “V”
                                             VPNRequestHandler<._showNewStyleDialog@resource:///org/gnome/shell/ui/components/networkAgent.js:522:29
                                             wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                             VPNRequestHandler<._readStdoutNewStyle/<@resource:///org/gnome/shell/ui/components/networkAgent.js:487:17
NetworkManager[3100]: <error> [1501680681.1824] vpn-connection[0x1c3a690,00cc105b-5927-4720-8747-423d980c3107,"MyVPN",0]: Failed to request VPN secrets #3: No agents were available for this request.
NetworkManager[3100]: <info>  [1501680681.1854] vpn-connection[0x1c3a690,00cc105b-5927-4720-8747-423d980c3107,"MyVPN",0]: VPN plugin: state changed: stopped (6)
```

However, if I use "Store the password for all users", everything works fine.

Info:

* Arch Linux x64
* Kernel 4.12.3 (I tried 4.9.40 LTS kernel as well)
* Gnome 3.25.4 (third-party repo: https://softwareperonista.com.ar/repo/archlinux/gnome-devel/x86_64/)
* networkmanager 1.8.2
* libnm 1.8.2
* networkmanager-l2tp 1.2.8

**Comment by dkosovic** [comment]
I usually track the the upstream changes, in particular the closely related network-manager-pptp :
   https://git.gnome.org/browse/?q=network-manager

But so far only network-manager-openvpn seems to have changes that require libnma >= 1.8.0 and libnm-gtk >= 1.8.0.

I'm guessing the NetworkManager VPN plugins will have their next version numbers bumped up to 1.8.0 and a new nm-1-2 git branch created for NetworkManager >= 1.2.0 and < 1.8.0 compatibility, much like there is a nm-1-0 branch for NetworkManager 1.0 compatibilty.

I think the wisest thing is to sit back and see what the GNOME Project does with their VPN plugins. I'm more than happy to back port their changes.

**Comment by dkosovic** [comment]
I've been able to reproduce with NetworkManager 1.8.2, but not with NetworkManager 1.8.4.

I think the bug was in libnma which handles the password storage for the NetworkManager VPN plugins.

**Comment by OlliC** [comment]
I have the same problem with networkmanager 1.10 on current Arch Linux.

**Comment by frol** [comment]
I cannot reproduce this anymore on my latest Arch Linux with NM 1.10.

@OlliC I think, you should bring more details of your setup (versions, logs, etc) since it works for me now, which means that all my info is not relevant anymore.

**Comment by dkosovic** [comment]
Thanks for the feedback, sorry for not responding earlier.

I'll incorporate the passwords storage issue and fix in the known issues of the wiki hopefully in the next few days.
