### ISSUE TITLE
make error "Failed to open file './properties/gresource.xml': No such file or directory"

### ISSUE THREAD

**Issue by stopanko** [nm-l2tp/network-manager-l2tp#57]
I am trying to build this manager but i have got an error.
**Steps:**
cd  network...
autoreconf -fi  
intltoolize 

./configure \
  --disable-static --prefix=/usr \
  --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu \
  --libexecdir=/usr/lib/NetworkManager \
  --localstatedir=/var \
  --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7

(tried just `./configure` without options)
**make**

**Got the error:**

Failed to open file './properties/gresource.xml': No such file or directory
  GEN      src/nm-l2tp-pppd-service-dbus.h
make  all-recursive
make[1]: Entering directory '/home/stopanko/network-manager-l2tp'
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
Failed to open file './properties/gresource.xml': No such file or directory
Making all in .
make[2]: Entering directory '/home/stopanko/network-manager-l2tp'
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
Failed to open file './properties/gresource.xml': No such file or directory
  CC       src/src_libnm_l2tp_pppd_service_dbus_la-nm-l2tp-pppd-service-dbus.lo
  CCLD     src/libnm-l2tp-pppd-service-dbus.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CC       shared/nm-utils/properties_libnm_vpn_plugin_l2tp_la-nm-vpn-plugin-utils.lo
  CC       properties/properties_libnm_vpn_plugin_l2tp_la-nm-l2tp-editor-plugin.lo
  CC       properties/properties_libnm_vpn_plugin_l2tp_la-import-export.lo
properties/import-export.c: In function ‘ip4_import_error’:
properties/import-export.c:132:15: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
               val);
               ^
  CCLD     properties/libnm-vpn-plugin-l2tp.la
  CC       shared/nm-utils/properties_libnm_vpn_plugin_l2tp_editor_la-nm-shared-utils.lo
make[2]: *** No rule to make target 'properties/gresource.xml', needed by 'properties/resources.c'.  Stop.
make[2]: Leaving directory '/home/stopanko/network-manager-l2tp'
Makefile:1420: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/stopanko/network-manager-l2tp'
Makefile:775: recipe for target 'all' failed
make: *** [all] Error 2

**My system**

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
NAME="Linux Mint"
VERSION="18.1 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
cat: /etc/upstream-release: Is a directory

**Comment by dkosovic** [comment]
I forgot to add `gresource.xml` file to the git repo. I'll add it in the next few hours when I'm back home.

But a couple of quick workarounds:

Use the latest stable release with the following git checkout :
 `git checkout tags/1.2.8`

Or copy `gresource.xml` from the following location and put it in `properties/` folder :
* https://git.gnome.org/browse/network-manager-pptp/plain/properties/gresource.xml

then replace all instances of pptp with l2tp in that file.

**Comment by dkosovic** [comment]
thanks, the missing gresource.xml file is now in this git repo.
