### ISSUE TITLE
Configured VPN not showing up under "VPN connections"

### ISSUE THREAD

**Issue by dvdmuckle** [nm-l2tp/network-manager-l2tp#6]
First off, thank you for maintaining this plugin. I have been tearing my hair out for the past three days on how to do L2TP/IPSEC on Ubuntu 16.04.

Running 16.04, I was able to configure an L2TP/IPSEC VPN. However, while I can see it under connections, it doesn't show up under enablable VPN connections. I don't if this has to do with previous reported issues, but from what it sounds network-manager-l2tp flat out doesn't work under 16.04.

**Comment by dkosovic** [comment]
I wasn't able to get L2TP/IPSEC to work with the xl2tpd-1.3.6 package that ships with Ubuntu 16.04.

But with NetworkManager-l2tp-1.2.2 I am able to get a L2TP/IPSEC VPN connection with a locally built xl2tpd installed to /usr/local/, i.e. :

````/bin/sh
sudo apt-get remove xl2tpd
sudo apt-get install libpcap0.8-dev

wget https://github.com/xelerance/xl2tpd/archive/v1.3.6/xl2tpd-1.3.6.tar.gz
tar xvzf xl2tpd-1.3.6.tar.gz
cd xl2tpd-1.3.6
make
sudo make install
````
At runtime, NetworkManager-l2tp looks at a number of places where the xl2tpd command might be installed, including /usr/local/sbin/xl2tpd

The Ubuntu xl2tpd-1.3.6 package is built with the -fstack-protector-strong gcc flag which is triggering the bug. I haven't looked properly yet where in the xl2tpd code it happens, but when I do, I will report it upstream.

Which version of xl2tpd are you using ?

**Comment by dkosovic** [comment]
Forgot to mention I do see configured connections under the "VPN connections" in the Unity network menu. If it's missing somewhere else let me know.

Might be related to a recent check-in I did in the last couple of days, so would recommend a git pull to the latest in the master branch or the 1.2.2 tag if you haven't already.

**Comment by dvdmuckle** [comment]
Okay, it was a matter of compiling xl2tpd from source. I was getting a cryptic error because I didn't install libcap0.8-dev, thanks for pointing that out. I think things are working now, the VPN shows up under configured VPNs and I can initiate it. Now for getting it to work... I'm using a guide for OS X from my university to connect to the VPN, so I reckon things will be different.
