### ISSUE TITLE
xl2tpd < 1.3.12  broken with kernels 4.15 and 4.16

### ISSUE THREAD

**Issue by dkosovic** [nm-l2tp/network-manager-l2tp#79]
See upstream xl2tpd issue for `udp_xmit failed ... with err=-1:No such device` error with kernels 4.15 and 4.16  :
* https://github.com/xelerance/xl2tpd/issues/147

**Comment by dkosovic** [comment]
Later versions of Kernel 4.14 are now affected by this bug, e.g. kernel  4.14.30 :
* https://github.com/xelerance/xl2tpd/issues/147#issuecomment-378510616

**Comment by dkosovic** [comment]
Unfortunately Ubuntu 18.04 is one of the few linux distributions that hasn't updated to xl2tpd 1.3.12 or backported the patch that contains a workaround for the kernel bug. The Ubuntu 18.04 bug report can be found here :

* https://bugs.launchpad.net/bugs/1760796

Please vote for the bug if it affects you and it will hopefully gain more attention and will eventually get fixed.

As a workaround, you can xl2tpd from source code :

```
sudo apt install build-essential git libpcap0.8-dev
sudo systemctl stop xl2tpd
git clone https://github.com/xelerance/xl2tpd.git
cd xl2tpd
make
sudo cp xl2tpd /usr/sbin/xl2tpd
```

**Comment by jfha73** [comment]
I tried compiling l2tp from source, but after I installed it and tried to connect, syslog shows this and not connecting (IP 1.2.3.4 is my local IP, 4.3.2.1 is the server IP)

> Jul  4 14:22:30 localhost NetworkManager[1147]: <info>  [1530728550.3723] vpn-connection[0x55611effc100,d2422233-fc6c-4e0b-be0e-1d5e16d7a810,"Gloss VPN",0]: Started the VPN service, PID 11561
Jul  4 14:22:30 localhost NetworkManager[1147]: <info>  [1530728550.3882] vpn-connection[0x55611effc100,d2422233-fc6c-4e0b-be0e-1d5e16d7a810,"Gloss VPN",0]: Saw the service appear; activating connection
Jul  4 14:22:30 localhost gnome-shell[6085]: VPN plugin at /usr/lib/NetworkManager/nm-openvpn-auth-dialog is not executable
Jul  4 14:22:30 localhost NetworkManager[1147]: <info>  [1530728550.6904] vpn-connection[0x55611effc100,d2422233-fc6c-4e0b-be0e-1d5e16d7a810,"Gloss VPN",0]: VPN connection: (ConnectInteractive) reply received
Jul  4 14:22:30 localhost nm-l2tp-service[11561]: Check port 1701
Jul  4 14:22:30 localhost nm-l2tp-service[11561]: Can't bind to port 1701
Jul  4 14:22:30 localhost NetworkManager[1147]: Stopping strongSwan IPsec...
Jul  4 14:22:30 localhost charon: 00[DMN] signal of type SIGINT received. Shutting down
Jul  4 14:22:30 localhost ipsec[2308]: 00[DMN] Starting IKE charon daemon (strongSwan 5.6.2, Linux 4.15.0-24-generic, x86_64)
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading ca certificates from '/etc/ipsec.d/cacerts'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading aa certificates from '/etc/ipsec.d/aacerts'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading ocsp signer certificates from '/etc/ipsec.d/ocspcerts'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading attribute certificates from '/etc/ipsec.d/acerts'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading crls from '/etc/ipsec.d/crls'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading secrets from '/etc/ipsec.secrets'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-7c04ea48-b58e-4cea-b1ad-0eea31579027.secrets'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-d2422233-fc6c-4e0b-be0e-1d5e16d7a810.secrets'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-fcd08bda-862b-42a1-aee5-b99889f6a459.secrets'
Jul  4 14:22:30 localhost ipsec[2308]: 00[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:30 localhost ipsec[2308]: 00[LIB] loaded plugins: charon aes rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac gcm attr kernel-netlink resolve socket-default connmark stroke updown eap-mschapv2 xauth-generic counters
Jul  4 14:22:30 localhost ipsec[2308]: 00[LIB] dropped capabilities, running as uid 0, gid 0
Jul  4 14:22:30 localhost ipsec[2308]: 00[JOB] spawning 16 worker threads
Jul  4 14:22:30 localhost ipsec[2308]: 00[DMN] signal of type SIGINT received. Shutting down
Jul  4 14:22:30 localhost ipsec[2308]: charon stopped after 200 ms
Jul  4 14:22:30 localhost ipsec[2308]: ipsec starter stopped
Jul  4 14:22:32 localhost NetworkManager[1147]: Starting strongSwan 5.6.2 IPsec [starter]...
Jul  4 14:22:32 localhost NetworkManager[1147]: Loading config setup
Jul  4 14:22:32 localhost NetworkManager[1147]: Loading conn 'd2422233-fc6c-4e0b-be0e-1d5e16d7a810'
Jul  4 14:22:32 localhost NetworkManager[1147]: found netkey IPsec stack
Jul  4 14:22:32 localhost charon: 00[DMN] Starting IKE charon daemon (strongSwan 5.6.2, Linux 4.15.0-24-generic, x86_64)
Jul  4 14:22:32 localhost charon: 00[CFG] loading ca certificates from '/etc/ipsec.d/cacerts'
Jul  4 14:22:32 localhost charon: 00[CFG] loading aa certificates from '/etc/ipsec.d/aacerts'
Jul  4 14:22:32 localhost charon: 00[CFG] loading ocsp signer certificates from '/etc/ipsec.d/ocspcerts'
Jul  4 14:22:32 localhost charon: 00[CFG] loading attribute certificates from '/etc/ipsec.d/acerts'
Jul  4 14:22:32 localhost charon: 00[CFG] loading crls from '/etc/ipsec.d/crls'
Jul  4 14:22:32 localhost charon: 00[CFG] loading secrets from '/etc/ipsec.secrets'
Jul  4 14:22:32 localhost charon: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-7c04ea48-b58e-4cea-b1ad-0eea31579027.secrets'
Jul  4 14:22:32 localhost charon: 00[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:32 localhost charon: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-d2422233-fc6c-4e0b-be0e-1d5e16d7a810.secrets'
Jul  4 14:22:32 localhost charon: 00[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:32 localhost charon: 00[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-fcd08bda-862b-42a1-aee5-b99889f6a459.secrets'
Jul  4 14:22:32 localhost charon: 00[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:32 localhost charon: 00[LIB] loaded plugins: charon aes rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac gcm attr kernel-netlink resolve socket-default connmark stroke updown eap-mschapv2 xauth-generic counters
Jul  4 14:22:32 localhost charon: 00[LIB] dropped capabilities, running as uid 0, gid 0
Jul  4 14:22:32 localhost charon: 00[JOB] spawning 16 worker threads
Jul  4 14:22:32 localhost charon: 05[CFG] received stroke: add connection 'd2422233-fc6c-4e0b-be0e-1d5e16d7a810'
Jul  4 14:22:32 localhost charon: 05[CFG] added configuration 'd2422233-fc6c-4e0b-be0e-1d5e16d7a810'
Jul  4 14:22:33 localhost charon: 07[CFG] rereading secrets
Jul  4 14:22:33 localhost charon: 07[CFG] loading secrets from '/etc/ipsec.secrets'
Jul  4 14:22:33 localhost charon: 07[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-7c04ea48-b58e-4cea-b1ad-0eea31579027.secrets'
Jul  4 14:22:33 localhost charon: 07[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:33 localhost charon: 07[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-d2422233-fc6c-4e0b-be0e-1d5e16d7a810.secrets'
Jul  4 14:22:33 localhost charon: 07[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:33 localhost charon: 07[CFG] loading secrets from '/etc/ipsec.d/nm-l2tp-ipsec-fcd08bda-862b-42a1-aee5-b99889f6a459.secrets'
Jul  4 14:22:33 localhost charon: 07[CFG]   loaded IKE secret for 4.3.2.1
Jul  4 14:22:33 localhost charon: 09[CFG] received stroke: initiate 'd2422233-fc6c-4e0b-be0e-1d5e16d7a810'
Jul  4 14:22:33 localhost charon: 11[IKE] initiating Main Mode IKE_SA d2422233-fc6c-4e0b-be0e-1d5e16d7a810[1] to 4.3.2.1
Jul  4 14:22:33 localhost charon: 11[ENC] generating ID_PROT request 0 [ SA V V V V V ]
Jul  4 14:22:33 localhost charon: 11[NET] sending packet: from 1.2.3.4[500] to 4.3.2.1[500] (204 bytes)
Jul  4 14:22:33 localhost charon: 12[NET] received packet: from 4.3.2.1[500] to 1.2.3.4[500] (40 bytes)
Jul  4 14:22:33 localhost charon: 12[ENC] parsed INFORMATIONAL_V1 request 0 [ N(NO_PROP) ]
Jul  4 14:22:33 localhost charon: 12[IKE] received NO_PROPOSAL_CHOSEN error notify
Jul  4 14:22:33 localhost NetworkManager[1147]: initiating Main Mode IKE_SA d2422233-fc6c-4e0b-be0e-1d5e16d7a810[1] to 4.3.2.1
Jul  4 14:22:33 localhost NetworkManager[1147]: generating ID_PROT request 0 [ SA V V V V V ]
Jul  4 14:22:33 localhost NetworkManager[1147]: sending packet: from 1.2.3.4[500] to 4.3.2.1[500] (204 bytes)
Jul  4 14:22:33 localhost NetworkManager[1147]: received packet: from 4.3.2.1[500] to 1.2.3.4[500] (40 bytes)
Jul  4 14:22:33 localhost NetworkManager[1147]: parsed INFORMATIONAL_V1 request 0 [ N(NO_PROP) ]
Jul  4 14:22:33 localhost NetworkManager[1147]: received NO_PROPOSAL_CHOSEN error notify
Jul  4 14:22:33 localhost NetworkManager[1147]: establishing connection 'd2422233-fc6c-4e0b-be0e-1d5e16d7a810' failed
Jul  4 14:22:34 localhost NetworkManager[1147]: Stopping strongSwan IPsec...
Jul  4 14:22:34 localhost charon: 00[DMN] signal of type SIGINT received. Shutting down
Jul  4 14:22:34 localhost nm-l2tp-service[11561]: g_dbus_method_invocation_take_error: assertion 'error != NULL' failed
Jul  4 14:22:34 localhost NetworkManager[1147]: <info>  [1530728554.3151] vpn-connection[0x55611effc100,d2422233-fc6c-4e0b-be0e-1d5e16d7a810,"Gloss VPN",0]: VPN plugin: state changed: stopped (6)
Jul  4 14:22:34 localhost NetworkManager[1147]: <info>  [1530728554.3193] vpn-connection[0x55611effc100,d2422233-fc6c-4e0b-be0e-1d5e16d7a810,"Gloss VPN",0]: VPN service disappeared
Jul  4 14:22:34 localhost NetworkManager[1147]: <warn>  [1530728554.3209] vpn-connection[0x55611effc100,d2422233-fc6c-4e0b-be0e-1d5e16d7a810,"Gloss VPN",0]: VPN connection: failed to connect: 'Message recipient disconnected from message bus without replying'

**Comment by dkosovic** [comment]
@jfha73 your issue has nothing to do with this issue as xl2tpd hasn't been invoked yet, it is failing at the IPsec connection stage with strongswan's charon. If you still need help after this comment, I'm happy to help, but it would be best to open a new issue.

Your issue is that the VPN server doesn't like the default proposals that strongswan is offering, hence the `NO_PROPOSAL_CHOSEN` error. See the _"Issue with VPN servers only proposing IPsec IKEv1 weak legacy algorithms"_ in the README.md file :
 * [https://github.com/nm-l2tp/network-manager-l2tp/tree/nm-1-2](https://github.com/nm-l2tp/network-manager-l2tp/tree/nm-1-2#issue-with-vpn-servers-only-proposing-ipsec-ikev1-weak-legacy-algorithms)

The best fix is to reconfigure the VPN server by adding proposals that don't have weak algorithms, but if you can't, you'll need to configure the Phase 1 and 2 Algorithms, see the README.md file for an example workaround for a proposal that uses the 3DES, SHA1 and MODP1024 broken algorithms.
