### ISSUE TITLE
cannot compile nm-l2tp

### ISSUE THREAD

**Issue by shebet** [nm-l2tp/network-manager-l2tp#80]
I am trying to compile and install the nm-l2tp on Ubuntu 16.04.4 x64  kernel 4.13.0-37-generic.
I receive this error message when I run ./autogen.sh 

> 

configure: error: Package requirements (libnma >= 1.8.0) were not met:

Requested 'libnma >= 1.8.0' but version of libnma is 1.2.6

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBNMA_CFLAGS
and LIBNMA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

> 
I cannot fix the library version issue. Any ideas?

**Comment by dkosovic** [comment]
Issue the following:
```
git checkout nm-1-2 
```
See the following for more details on building :
* https://github.com/nm-l2tp/network-manager-l2tp/wiki/Building

If you want to use the pre-built PPA packages instead, see:
```
https://github.com/nm-l2tp/network-manager-l2tp/wiki/Prebuilt-Packages#ubuntu-1404-1604-and-1704-mint-17x-and-18x
``
