### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by BenjaminEHowe** [nm-l2tp/network-manager-l2tp#81]
It looks like `network-manager-l2tp` doesn't support IPv6. Please could support be considered?

**Comment by dkosovic** [comment]
xl2tpd doesn't support IPv6, so I've never really considered adding IPv6 support.

The xl2tpd ipv6 branch in GitHub hasn't been touched in 7 years and I'm not sure if it will even build or work with modern linux kernels:
* https://github.com/xelerance/xl2tpd/tree/ipv6

**Comment by dkosovic** [comment]
A delayed IPv6 news update, but here’s a follow‑up just for completeness

xl2tpd still doesn't have IPv6 support.

kl2tpd from the go-l2tp package supports IPv6 and it is now the primary L2TP daemon for NetworkManager-l2p, which fallbacks to xl2tpd if it can't find kl2tpd.

NetworkManager-l2tp 1.52.2 now has experimental IPv6 support if kl2tpd is being used.
