### ISSUE TITLE
Packaging ubuntu

### ISSUE THREAD

**Issue by lunixoid** [nm-l2tp/network-manager-l2tp#82]
Hi.
I have an issue with install package network-manager-l2tp from ppa nm-l2tp/network-manager-l2tp.
After installing package - the plugin does not work.
After installing package network-manager-l2tp-gnome - the plugin works fine.
I think it could be fixed in DEBIAN/control file of package network-manager-l2tp, just place dependence  to network-manager-l2tp-gnome.

**Comment by dkosovic** [comment]
Problem is that KDE users screamed to have the dependencies on GNOME removed from all NetworkManager VPN plug-ins (not just this one) and they ended up getting their wish which resulted in separate _*-gnome_ packages.

KDE Plasma provides it's own GUI front-end to all the major NetworkManager VPN plugins including network-manager-l2tp.

In the PPA instructions on the following page :
* https://launchpad.net/~nm-l2tp/+archive/ubuntu/network-manager-l2tp

I explicitly have:
```
sudo apt install network-manager-l2tp network-manager-l2tp-gnome
```
