### ISSUE TITLE
vpn: (l2tp,/etc/NetworkManager/VPN/nm-l2tp-service.name) cannot load legacy-only plugin

### ISSUE THREAD

**Issue by rogoznikoviv** [nm-l2tp/network-manager-l2tp#90]
calculate /home/guest # emerge net-misc/networkmanager-l2tp

calculate /home/guest # nm-connection-editor 

**(nm-connection-editor:19488): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
** Message: vpn: (l2tp,/etc/NetworkManager/VPN/nm-l2tp-service.name) cannot load legacy-only plugin**

**Comment by dkosovic** [comment]
I suspect you are using a network-manager-l2tp < 1.2.

Please upgrade to network-manager-l2tp 1.2.10, the package you are using is something old that has built a legacy plugin with libnm-glib and doesn't include a new plugin using the new NetworkManager API.
