### ISSUE TITLE
autogen.sh error

### ISSUE THREAD

**Issue by username34** [nm-l2tp/network-manager-l2tp#98]
user@hostname:~/network-manager-l2tp-master$ ./autogen.sh
configure.ac:148: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:148: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:148: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
user@hostname:~/network-manager-l2tp-master$

**Comment by dkosovic** [comment]
You need to install the libtool and intltool packages.

See the following on how to build on Ubuntu :
 https://github.com/nm-l2tp/network-manager-l2tp/wiki/Building

**Comment by username34** [comment]
Is it possible, being in one OS, to install programs in another OS?

I have configured internet l2tp on ubuntu, and there is a second OS - debian, where the internet is not configured.

I found the network-manager-l2tp program on github, and I try to install it, but there are a lot of dependencies. That is, I have to boot into ubuntu, search the Internet for one of the auxiliary programs, download, reboot the PC to debian, try to install the downloaded file, and so on.

**Comment by username34** [comment]
To fix it i installed libssl-dev, libnss3-dev

**Comment by username34** [comment]
After that i got error

> checking for LIBNMA... no
> configure: error: Package requirements (libnma >= 1.8.0) were not met:
> 
> Requested 'libnma >= 1.8.0' but version of libnma is 1.4.4
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables LIBNMA_CFLAGS
> and LIBNMA_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

**Comment by dkosovic** [comment]
I would recommend issuing `git checkout 1.2.10` to checkout the latest stable release. It should build fine on Debian 9.

The master branch only works with newer NetworkManager > 1.8 based Linux distros.

Only the `sudo make install` needs sudo (i.e. root) privileges, the other commands can be run as your user.

I previously tried twice to get network-manager-l2tp backported to Debian 9, but wasn't able to find a sponsor who could upload it. I do have a sponsor for Debian Sid, but he doesn't do backports.

The Debian and Ubuntu versions would need to be close relatives to do what you asked. Ubuntu 18.04 would be too new for Debian 9 as it has dropped the legacy libnm-glib support, but earlier Ubuntu version might work.

**Comment by dkosovic** [comment]
Forgot to mention after the first time you run `sudo make install` , you will need to logout of the GNOME desktop or reboot. It is an issue with nm-applet not detecting the corresponding VPN plugin has been installed. You won't need to do that for subsequent installs.

**Comment by username34** [comment]
> The master branch only works with newer NetworkManager > 1.8 based Linux distros.

in my OS network-manager 1.14.4 installed

> Only the `sudo make install` needs sudo (i.e. root) privileges, the other commands can be run as your user.

after i executed 
>sudo make install
and rebooted connection type l2tp was found in network-manager gui

and L2TP works.

And now should i remove directory network-manager-l2tp-master or it is using?

Can i setup autoconnect l2tp on startup?

> I previously tried twice to get network-manager-l2tp backported to Debian 9, but wasn't able to find a sponsor who could upload it. I do have a sponsor for Debian Sid, but he doesn't do backports.

i dont like debian 9, i am using crunchbangplusplus, it is a fork of debian 9 with its own repository

**Comment by dkosovic** [comment]
Once installed, the source code directory isn't required anymore, so can safely be deleted.

For auto-connecting a VPN connection, you need to run `nm-connection-editor` to enable it, see:
* https://askubuntu.com/questions/1048352/bionic-how-can-i-automatically-enable-vpn-on-a-network-connection

I haven't tried auto-connecting a VPN connection myself.

Interesting, I hadn't heard of crunchbangplusplus till now.

**Comment by username34** [comment]
> For auto-connecting a VPN connection, you need to run `nm-connection-editor` to enable it

There is no auto-connect option in VPN settings. 

I created text-file with password of vpn and removed password from settings.
`echo "vpn.secrets.password:MY_PASSWORD" > /home/user/beeline.parol`

I added 2 lines to my startup config file /home/user/.config/openbox/autostart 
```
sleep 2s && \
nmcli con up id beeline passwd-file /home/user/beeline.parol > /home/user/beeline.logfile &
```
And now vpn autoconnects fine.

**Comment by dkosovic** [comment]
Glad to hear you solved your issues and you got auto-connect working.

I'll now close this issue.
