### ISSUE TITLE
problem with debug

### ISSUE THREAD

**Issue by codex7** [nm-l2tp/network-manager-l2tp#99]
when i use this command :
`sudo /usr/libexec/nm-l2tp-service --debug`

i get this error: 

```
nm-l2tp[21423] <debug> nm-l2tp-service (version 1.2.10-1.el7) starting...
nm-l2tp[21423] <debug>  uses default --bus-name "org.freedesktop.NetworkManager.l2tp"
nm-l2tp[21423] <warn>  Failed to initialize a plugin instance: Connection ":1.2522" is not allowed to own the service "org.freedesktop.NetworkManager.l2tp" due to security policies in the configuration file
```

please help

**Comment by dkosovic** [comment]
I've never encountered the issue myself, but suspect you need to reset the Dbus service, e.g:
* https://archive.realvnc.com/pipermail/vnc-list/2007-September/058100.html


Unfortunately not all debug messages go stdout/stderr, there would be some in the `journalctl` output, there may be something there about the DBus issue.

**Comment by codex7** [comment]
i found solution, i disabled selinux and problem solved
